openapi: 3.1.0
info:
  title: 梁寧莉 自拍提示詞助手
  version: 1.0.0
  description: 根據自拍情境，生成符合梁寧莉個性提示詞
servers:
  - url: https://liang-ning-li-project-new.vercel.app
    description: 部署網址
paths:
  /api/generate:
    post:
      operationId: generatePrompt
      summary: 生成梁寧莉自拍提示詞
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NingliInput"
      responses:
        '200':
          description: 成功產生提示詞
          content:
            application/json:
              schema:
                type: object
                properties:
                  prompt:
                    type: string
                    description: 自拍提示詞
components:
  schemas:
    NingliInput:
      type: object
      required:
        - prompt
        - target
        - ai
        - background
      properties:
        prompt:
          type: string
          description: 梁寧莉中文描述詞，例如「逛美術館」
        target:
          type: string
          enum: [自拍, 他拍]
          description: 主體是誰
        ai:
          type: string
          description: 上傳者角色，例如「我」或「梁寧莉」
        background:
          type: string
          description: 場景與地點
        style:
          type: string
          description: 攝影風格（選填）
        expression:
          type: string
          description: 表情描述（選填）
        action:
          type: string
          description: 動作描述（選填）
        framing:
          type: string
          description: 構圖角度（選填）
